# Generated by Django 4.0.5 on 2022-07-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=4000)),
                ('outcome', models.CharField(max_length=1000)),
                ('amend_date', models.DateField(auto_now=True)),
                ('amend_time', models.TimeField(auto_now=True)),
                ('summary_trans', models.CharField(max_length=1000)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
