# Generated by Django 3.2.8 on 2021-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=30)),
                ('amend_date', models.DateField(auto_now=True)),
                ('amend_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
