# Generated by Django 4.0.5 on 2022-07-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user_name',
            new_name='user',
        ),
    ]
