# Generated by Django 3.2.8 on 2021-11-05 21:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_complaint_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='topic_data',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
