# Generated by Django 3.2.8 on 2021-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_complaint_topic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='topic_data',
            field=models.CharField(max_length=500),
        ),
    ]
