# Generated by Django 3.2.8 on 2021-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_complaint_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(default=['0.1', '0.2'], max_length=100),
            preserve_default=False,
        ),
    ]
