# Generated by Django 3.2.9 on 2021-11-15 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_complaint_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='good_or_servive',
            field=models.CharField(choices=[('CG', 'Consumer Goods'), ('ED', 'Education'), ('EAW', 'Energy and Water'), ('FS', 'Financial Services'), ('GEN', 'General Consumer Services'), ('HEL', 'Health'), ('LES', 'Leisure Services'), ('POE', 'Postal and Electronic Services'), ('TRN', 'Transport Services'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='occurence_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='details',
            field=models.CharField(max_length=4000),
        ),
    ]
