# Generated by Django 3.2.9 on 2021-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20211115_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='contacted_company',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
