# Generated by Django 3.2.9 on 2021-11-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211116_1924'),
        ('members', '0009_complaint_contacted_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='company',
        ),
        migrations.AddField(
            model_name='complaint',
            name='company_name',
            field=models.ForeignKey(default='Test', on_delete=django.db.models.deletion.CASCADE, to='company.company_model'),
            preserve_default=False,
        ),
    ]
