# Generated by Django 3.2.9 on 2021-11-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20211116_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='good_or_servive',
            new_name='good_or_service',
        ),
        migrations.AddField(
            model_name='complaint',
            name='outcome',
            field=models.CharField(default='I would like a full refund and for them to apologise', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='rights_breached',
            field=models.CharField(choices=[('CG', 'Consumer Goods'), ('ED', 'Education'), ('EAW', 'Energy and Water'), ('FS', 'Financial Services'), ('GEN', 'General Consumer Services'), ('HEL', 'Health'), ('LES', 'Leisure Services'), ('POE', 'Postal and Electronic Services'), ('TRN', 'Transport Services'), ('OTH', 'Other')], max_length=12, null=True),
        ),
    ]
