# Generated by Django 3.2.9 on 2021-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20211116_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='rights_breached',
            field=models.CharField(choices=[('TRUTHFUL_AD', 'Truthful Advertising'), ('FAULTY_GDS', 'Faulty Goods/Replacement'), ('CNTRCT', 'Unfair Contract'), ('RETURNS', 'Return of Goods within 14 Days'), ('EQUAL_ACCESS', 'Fair Access to Goods and Services')], max_length=12, null=True),
        ),
    ]
