# Generated by Django 3.2.9 on 2021-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_complaint_rights_breached'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='summarise',
            field=models.CharField(default='This was a test and did not run the model', max_length=500),
            preserve_default=False,
        ),
    ]
