# Generated by Django 4.0.5 on 2022-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_rename_summarise_complaint_summary_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='summary_trans',
            field=models.CharField(max_length=1000),
        ),
    ]
