version: "2"

services:
    django-apache2:
      build: .
      container_name: gpt3_or
      ports:
        - '80:80'
        - '3500:3500'
        - '443:443'

      volumes:
        - /etc/apache2/certificate/:/etc/apache2/certificate/
        - /etc/django/:/etc/django/
        - /etc/apache2/sites-available/:/etc/apache2/sites-available/