# Generated by Django 3.2.9 on 2021-11-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('complaint_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('twitter', models.CharField(max_length=200)),
                ('number_complaints', models.IntegerField()),
                ('number_resolutions', models.IntegerField()),
            ],
        ),
    ]
