# Generated by Django 3.2.9 on 2021-11-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_complaint_contacted_company'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='company_model',
        ),
        migrations.RenameField(
            model_name='company_model',
            old_name='company',
            new_name='company_name',
        ),
    ]
