# Generated by Django 3.2.9 on 2021-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211116_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='company_model',
            name='company_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
