# Generated by Django 3.2.9 on 2021-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211116_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_model',
            name='number_complaints',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company_model',
            name='number_resolutions',
            field=models.IntegerField(null=True),
        ),
    ]
